version: '3.9'
services:
  postgres:
    image: 'postgres:14.1'
    command: postgres -c 'max_connections=100' -c 'fsync=off' -c 'full_page_writes=off'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
  redis:
    image: 'redis:6.2.6'
    ports:
      - "6379:6379"
